### PR TITLE
Fix clear person to clear appointments

### LINKED ISSUE #209: Clearing person list should clear appointment list
**Describe the bug**
Clearing the person does not clear the appointment list, causing a read error at the start of the work.

**Steps to Reproduce**
1. Run the command `clear person`
2. Close the application
3. Open the application

**Expected behavior**
The appointment list should be cleared too.

### PR DESCRIPTION
**Pull request by zaidansani**
Resolves #209

### CODE REVIEW

File: src/main/java/seedu/address/model/appointment/Appointment.java [hunk 1]
```diff
@@ -150,7 +150,7 @@ public String toString() {
                 .add("appointmentId", appointmentId)
                 .add("person", person)
                 .add("appointmentType", getAppointmentType())
-                .add("appointmentDateTime", getAppointmentDateTime())
+                .add("appointmentDateTime", getAppointmentDateTime().toString())
```
Comment (jayjay19630) [inline src/main/java/seedu/address/model/appointment/Appointment.java:153]: Thanks for correcting the string method!

**Review by jayjay19630 — APPROVED** [review]
LGTM
