### PR TITLE
Fix: parser code quality changes

### LINKED ISSUE #216: Check parser for Code quality
Ensure the command parsers are upto the coding standards. Ensure, principles like SLAP are being reinforced

### PR DESCRIPTION
**Pull request by Vangmay**
fixes #216

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 1]
```diff
@@ -54,57 +54,113 @@ public AddCommand parse(String args) throws ParseException {
...
-            Name name = ParserUtil.parseName(argMultimap.getValue(PREFIX_NAME).get());
-            Phone phone = ParserUtil.parsePhone(argMultimap.getValue(PREFIX_PHONE).get());
-            Email email = ParserUtil.parseEmail(argMultimap.getValue(PREFIX_EMAIL).get());
-            Address address = ParserUtil.parseAddress(argMultimap.getValue(PREFIX_ADDRESS).get());
-            Status status = ParserUtil.parseStatus(argMultimap.getValue(PREFIX_STATUS).get());
-            Set<Tag> tagList = ParserUtil.parseTags(argMultimap.getAllValues(PREFIX_TAG));
-
-            PersonDescriptor person = new PersonDescriptor(name, phone, email, address, status, tagList);
-
+            PersonDescriptor person = parseAddPerson(argMultimap);
```
Comment (zaidansani) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java:57]: Excellent - this is what I meant by the SLAP.
The cut down into shorter methods should also help for readability!

**Review by zaidansani — APPROVED** [review]
LGTM! Code coverage dropped, but it's probably just because of the repositioning of lines. There's no introduction of actual new functional code
