### PR TITLE
Fix date format

### LINKED ISSUE #199: Incorrect date input
add appt i/2 ty/type d/2024-02-30 14:20:30
and add appt i/2 ty/type d/2024-02-31 14:20:30
Registers as 2024-02-29.
Fix so these are invalid inputs

### LINKED ISSUE #203: User guide documentation shows wrong example for date format
**Describe the bug**
The user guide shows the wrong example for the date format. See screenshot below.

**Screenshots**
image

### LINKED ISSUE #204: Find appointment example is inaccurate
**Describe the bug**
Example given gives wrong expected output

**Screenshots**
image

### LINKED ISSUE #205: Find appointment date format is inaccurate
**Describe the bug**
Date format specified does not match example.

**Screenshots**
image

### LINKED ISSUE #207: Remove seconds from DATE_TIME
**Describe the bug**
Currently the DATE_TIME requires YYYY/MM/DD hh:mm:ss. We can remove the seconds since it is unnecessary. It is not shown in the UI as well. 

**Screenshots**
Screenshot 2024-11-04 at 12 11 03

### PR DESCRIPTION
**Pull request by rxchell**
Fixes #203. Fixes #204. Fixes #205. Fixes #207. Fixes #199.

### CODE REVIEW

File: src/main/java/seedu/address/commons/util/DateUtil.java [hunk 1]
```diff
@@ -35,4 +38,15 @@ public static List<LocalDate> convertToDateList(String args) throws ParseExcepti
...
     }
+
+    /**
+     * Returns a formatted local date in the form of month date, year, time.
+     *
+     * @param appointmentDateTime the date and time to be formatted.
+     * @return a formatted string.
+     */
+    public static String formatDateTimeForDisplay(LocalDateTime appointmentDateTime) {
+        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MMMM dd, yyyy, hh:mm a").withLocale(Locale.US);
```
Comment (zaidansani) [inline src/main/java/seedu/address/commons/util/DateUtil.java:49]: Would it be better to have a public variable `formatter`, which is used universally by all things needing a formatter?

File: src/test/java/seedu/address/commons/util/DateUtilTest.java [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+    }
+
+    @Test
+    public void formatDateTimeForDisplay_validDateTime_returnsFormattedString() {
+        LocalDateTime dateTime = LocalDateTime.of(2023, 10, 1, 10, 0);
+        String expected = "October 01, 2023, 10:00 AM";
+        Locale.setDefault(Locale.US);
+        assertEquals(expected, DateUtil.formatDateTimeForDisplay(dateTime));
+    }
+}
```
Comment (choiwab) [inline src/test/java/seedu/address/commons/util/DateUtilTest.java:56]: Should we add more negative test cases?
Other than that, LGTM.
